# Copyright 2015 Google Inc. All Rights Reserved.
runtime: php55
api_version: 1
threadsafe: true

handlers:
# tell appengine where our static assets live
- url: /bundles
  static_dir: web/bundles

# the symfony front controller
- url: /.*
  script: web/app.php

# [START env_vars]
env_variables:
  SYMFONY_ENV: prod
# [END env_vars]

# Do not deploy bundle tests
skip_files:
  - (.*/)?Tests\/(.*)
